import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { createJiti } from 'jiti'
const jiti = createJiti(import.meta.url)
const { parseReplay, latestAt, fixAt, createDemoReplay, trailColor } = await jiti.import('../lib/tactical/replay.ts')
assert.equal(trailColor({ throttle: 0, brake: 0 }), '#ffc568', 'coasting is never braking red')
assert.equal(trailColor({ throttle: 100, brake: 100 }), '#ff564a', 'braking takes precedence')
assert.equal(trailColor({ throttle: 100, brake: 0 }), '#58ff9b')
assert.equal(trailColor(), '#7c92aa')
const rec = (ms, x, extra = {}) => ({ driver_number: 1, date: new Date(ms).toISOString(), x, y: 2, ...extra })
const data = parseReplay({ location: [rec(2000, 20), rec(1000, 10), rec(1000, 11)], car_data: [{ driver_number: 1, date: new Date(1500).toISOString(), throttle: 80 }] })
assert.equal(data.start, 1000)
assert.equal(data.drivers[0].fixes.length, 2)
assert.equal(fixAt(data.drivers[0].fixes, 1500).x, 15.5)
assert.equal(fixAt(data.drivers[0].fixes, 999), undefined, 'never show a future fix')
assert.equal(latestAt(data.drivers[0].car, 1400), undefined, 'never join future telemetry')
assert.equal(latestAt(data.drivers[0].car, 4100), undefined, 'stale telemetry expires')
assert.equal(fixAt([ {t: 1000, x: 1, y: 2, z: 0}, {t: 10000, x: 90, y: 2, z: 0} ], 1500).x, 1, 'do not interpolate across outages')
assert.throws(() => parseReplay([rec(1000, 'bad'), rec(2000, 2)]), /Invalid x/)
assert.throws(() => parseReplay([rec(1000, 1, {session_key: 1}), rec(2000, 2, {session_key: 2})]), /one session/)
assert.throws(() => parseReplay([rec(1000, 1), rec(1000, 2)]), /non-zero/)
assert.throws(() => parseReplay({location: [rec(1000, 1), rec(2000, 2)], car_data: {}}), /array/)
assert.equal(parseReplay([rec(1000, 0, {y: 0}), rec(2000, 2), rec(3000, 3)]).start, 2000, 'no-fix origin sentinel excluded')
assert.throws(() => parseReplay([rec(1000, 0, {y: 0}), rec(2000, 0, {y: 0})]), /non-zero/)
assert.equal(createDemoReplay().synthetic, true)
assert.equal(createDemoReplay().drivers.length, 4)
const captured = parseReplay(JSON.parse(readFileSync(new URL('../fixtures/openf1-location-zandvoort-2024.json', import.meta.url), 'utf8')))
assert.equal(captured.drivers.length, 20, 'captured OpenF1 window retains every driver')
assert.ok(captured.end > captured.start)
assert.ok(captured.drivers.every(d => d.car.length === 0), 'position-only imports never fabricate telemetry')
console.log('PASS tactical replay: sorting, duplicates, interpolation, stale joins, invalid input, session isolation, explicit demo')
