import assert from 'node:assert/strict'
import { createJiti } from 'jiti'
const jiti = createJiti(import.meta.url)
const { parseCommand } = await jiti.import('../lib/tactical/commands.ts')
assert.deepEqual(parseCommand('Engineer, activate Thermal!'), { type: 'mode', mode: 'thermal' })
assert.deepEqual(parseCommand('Engineer, restore normal'), { type: 'mode', mode: 'default' })
assert.deepEqual(parseCommand('turn off thermal'), { type: 'mode', mode: 'default' })
assert.equal(parseCommand('Engineer, activate Night Vision!'), null)
assert.deepEqual(parseCommand('Engineer, track Max Verstappen'), { type: 'track-driver', query: 'max verstappen' })
assert.deepEqual(parseCommand('track car 44'), { type: 'track-driver', query: '44' })
assert.deepEqual(parseCommand('display interval gaps'), { type: 'intervals', visible: true })
assert.deepEqual(parseCommand('hide gaps'), { type: 'intervals', visible: false })
assert.deepEqual(parseCommand('chase cam'), { type: 'camera', mode: 'chase' })
assert.deepEqual(parseCommand('follow camera'), { type: 'camera', mode: 'follow' })
assert.equal(parseCommand('do not activate night vision'), null)
assert.equal(parseCommand('night vision and delete everything'), null)
assert.equal(parseCommand(''), null)
assert.equal(parseCommand('track'), null)
console.log('Tactical command grammar: 14 checks passed')
